djangopeople/urls.py
# python
import os

# django
from django.conf.urls.defaults import *
from django.conf import settings
from djangopeople.models import KungfuPerson
from djangopeople.feeds import LatestAll, LatestPeople

# app
from djangopeople import views

feeds = {
    'people': LatestPeople,
    'all': LatestAll,
}

urlpatterns = patterns('',
    url(r'^$', views.index, name="index"),
    url(r'^club/([A-Za-z0-9-:]{3,})/$', views.club, name="club.view"),
    url(r'^clubs/$', views.clubs_all, name="clubs_all"),
    url(r'^style/([A-Za-z0-9-:]{3,})/$', views.style, name="style.view"),

    url(r'^all/(clubs|styles|people|photos)/$', views.all_something,
        name="all_something"),
    url(r'^all/(clubs|styles|people|photos)/by-date/$', views.all_something,
        {'sort_by':'date'}, name="all_something_by_date"),

    (r'^login/$', views.login),
    (r'^logout/$', views.logout),
    (r'^recent/$', views.recent),
    (r'^recover/$', views.lost_password),
    (r'^recover/([a-z0-9]{3,})/([a-f0-9]+)/([a-f0-9]{32})/$',
        views.lost_password_recover),
    url(r'^leavesite/$', views.leave_site, name="leave_site"),
    (r'^leavesite/([a-z0-9]{3,})/([a-f0-9]+)/([a-f0-9]{32})/$',
        views.leave_site_confirm),
    url(r'^leavesite/left/$', views.left_site, name="left_site"),

    url(r'^signup/$', views.signup, name="signup"),
    url(r'^wall/$', views.wall, name="wall"),
    url(r'^zoom/$', views.zoom, name="zoom"),
    url(r'^zoom-content/$', views.zoom_content, name="zoom_content"),
    url(r'^zoom-content.json$', views.zoom_content_json, name="zoom_content_json"),

    url(r'^swf_upload_test/$', views.swf_upload_test),

    (r'^guess-club-name.json$', views.guess_club_name_json),
    (r'^guess-username.json$', views.guess_username_json),
    url(r'^find-clubs-by-location.json$', views.find_clubs_by_location_json),

    url(r'^_nav.html$', views.nav_html, name="nav_html"),
    url(r'^search/$', views.search, name="search"),
    url(r'^tinymcefilebrowser/$', views.tinymce_filebrowser,
       name="tinymce.filebrowser"),
    url(r'^runway/$', views.runway, name="runway"),
    url(r'^runway/data.js$', views.runway_data_js, name="runway_data_js"),
    url(r'^crossdomain.xml$', views.crossdomain_xml, name="crossdomain_xml"),

    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed',
        {'feed_dict': feeds}),

    url(r'^([a-z]{2})/$', views.country, name="country"),
    (r'^([a-z]{2})/sites/$', views.country_sites),
    (r'^([a-z]{2})/(\w+)/$', views.region),

    url(r'^([a-z0-9]{3,})/$', views.profile, name="person.view"),
    url(r'^([a-z0-9]{3,})/crop-profile-photo/$', views.crop_profile_photo,
        name="crop_profile_photo"),
    url(r'^([a-z0-9]{3,})/_user-info.html$', views.user_info_html,
        name="user_info_html"), # used by runway

    url(r'^([a-z0-9]{3,})/_user-info-map.html$', views.user_info_html,
        {'include_photo':True},
        name="user_info_html"), # used by worldmap
    url(r'^([a-z0-9]{3,})/password/$', views.edit_password, name="edit_password"),
    url(r'^all-videos/$', views.videos_all, name="videos_all"),
    url(r'^([a-z0-9]{3,})/videos/add/$', views.add_video, name="add_video"),
    url(r'^([a-z0-9]{3,})/video/(\d+)/$', views.video, name="video.view"),
    url('^get_youtube_video_by_id.json$', views.get_youtube_video_by_id_json),
    (r'^([a-z0-9]{3,})/club/delete/([a-z0-9-:]{3,})/$', views.delete_club_membership),
    url(r'^([a-z0-9]{3,})/style/delete/([a-z0-9-:]{3,})/$', views.delete_style,
       name="delete_style"),
    url(r'^([a-z0-9]{3,})/videos/delete/(\d+)/$', views.delete_video, name="delete_video"),

    url(r'^([a-z0-9]{3,})/diary/add/$', views.diary_entry_add, name="add_diary_entry"),
    (r'^([a-z0-9]{3,})/diary/([a-z0-9-]{3,})/delete/$', views.diary_entry_delete),
    (r'^([a-z0-9]{3,})/diary/([a-z0-9-]{3,})/edit/$', views.diary_entry_edit),
    url(r'^([a-z0-9]{3,})/diary/([a-z0-9-]{3,})/location.json$', views.diary_entry_location_json),
    url(r'^([a-z0-9]{3,})/diary/([a-z0-9-]{3,})/$', views.diary_entry, name="diaryentry.view"),
    url(r'^([a-z0-9]{3,})/club/$', views.edit_club, name="edit_club"),
    url(r'^([a-z0-9]{3,})/style/$', views.edit_style, name="edit_style"),
    url(r'^([a-z0-9]{3,})/photo/(\d+)/delete/$', views.photo_delete, name="photo.delete"),
    url(r'^([a-z0-9]{3,})/photo/(\d+)/edit/$', views.photo_edit, name="photo.edit"),
    url(r'^([a-z0-9]{3,})/photo/(\d+)/$', views.photo, name="photo.view"),
    url(r'^([a-z0-9]{3,})/viewallphotos/$', views.viewallphotos),
    url(r'^([a-z0-9]{3,})/photo/upload/$', views.photo_upload,
        {'prefer':'multiple'}, name="upload_photo"),
    url(r'^([a-z0-9]{3,})/photo/upload/single/$', views.photo_upload,
        {'prefer':'single'}),
    #url(r'^([a-z0-9]{3,})/photo/upload/multiple/$', views.photo_upload),
    url(r'^([a-z0-9]{3,})/photo/upload/pre/$', views.photo_upload_multiple_pre),

    url(r'^([a-z0-9]{3,})/profile/$', views.edit_profile, name="edit_profile"),
    (r'^([a-z0-9]{3,})/location/$', views.edit_location),
    url(r'^([a-z0-9]{3,})/profileupload/$', views.upload_profile_photo,
        name="upload_profile_photo"),
    url(r'^([a-z0-9]{3,})/profileupload/webcam/$', views.webcam_profile_photo,
        name="webcam_profile_photo"),
    #(r'^([a-z0-9]{3,})/upload/done/$', views.upload_done),
    (r'^([a-z0-9]{3,})/whatnext/$', views.whatnext),
    url(r'^([a-z0-9]{3,})/newsletter/options/$', views.newsletter_options,
       name="newsletter.options"),
)

urls.py
import os

from django.conf.urls.defaults import *
from django.conf import settings
from django.http import HttpResponseRedirect
import django.views.static
from django.contrib import admin
admin.autodiscover()

from djangopeople import views
from djangopeople.models import KungfuPerson



def redirect(url):
    return lambda res: HttpResponseRedirect(url)

from djangopeople.sitemaps import FlatPageSitemap, sitemap, CustomSitemap

sitemaps = {
    'flatpages': FlatPageSitemap,
    'otherpages': CustomSitemap,
}


urlpatterns = patterns('',
    (r'^admin/', include(admin.site.urls)),
    (r'^stats/', include('stats.urls')),
                      
    (r'', include('djangopeople.urls')),
    (r'^newsletters/', include('newsletter.urls')),
    (r'^welcome/', include('welcome.urls')),
    (r'^twitter/', include('twitter.urls')),
                       
    (r'^sitemap.xml$', sitemap,
     {'sitemaps': sitemaps}),

    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
        'show_indexes': False
    }),
                       
)

if settings.DEBUG:
    
    # When not in debug mode (i.e. development mode)
    # nothing django.views.static.serve should not be used at all.
    # If it is used it means that nginx config isn't good enough.
    
    urlpatterns += patterns('', 
                            
        # CSS, Javascript and IMages
        (r'^webcam/(?P<path>.*)$', django.views.static.serve,
         {'document_root': settings.MEDIA_ROOT + '/webcam',
           'show_indexes': False}),                       
        (r'^img/(?P<path>.*)$', django.views.static.serve,
         {'document_root': settings.MEDIA_ROOT + '/img',
           'show_indexes': False}),                       
        (r'^css/(?P<path>.*)$', django.views.static.serve,
          {'document_root': settings.MEDIA_ROOT + '/css',
           'show_indexes': False}),
        (r'^js/(?P<path>.*)$', django.views.static.serve,
          {'document_root': settings.MEDIA_ROOT + '/js',
           'show_indexes': False}),
    
    )

djangopeople/forms.py
# python
import os
import re
import base64
from urlparse import urlparse
import tempfile

# django
from django import forms
from django.forms.forms import BoundField
from django.db.models import ObjectDoesNotExist
from django.conf import settings

from groupedselect import GroupedChoiceField
from models import KungfuPerson, Country, Region, User, RESERVED_USERNAMES, Club, DiaryEntry, Photo

from youtube import YouTubeVideoError, get_youtube_video_by_id, video_url_or_id
from utils import is_jpeg


try:
    from BeautifulSoup import BeautifulSoup
except ImportError:
    import warnings
    warnings.warn("BeautifulSoup not installed (easy_install BeautifulSoup)")
    BeautifulSoup = None

def region_choices():
    # For use with GroupedChoiceField
    regions = list(Region.objects.select_related().order_by('country', 'name'))
    groups = [(False, (('', '---'),))]
    current_country = False
    current_group = []
    
    for region in regions:
        if region.country.name != current_country:
            if current_group:
                groups.append((current_country, current_group))
                current_group = []
            current_country = region.country.name
        current_group.append((region.code, region.name))
    if current_group:
        groups.append((current_country, current_group))
        current_group = []
    
    return groups

def not_in_the_atlantic(self):
    if self.cleaned_data.get('latitude', '') and self.cleaned_data.get('longitude', ''):
        lat = self.cleaned_data['latitude']
        lon = self.cleaned_data['longitude']
        if 43 < lat < 45 and -39 < lon < -33:
            raise forms.ValidationError("Drag and zoom the map until the crosshair matches your location")
    return self.cleaned_data['location_description']

class SignupForm(forms.Form):

    # Fields for creating a User object
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    email = forms.EmailField()
    username = forms.RegexField('^[a-zA-Z0-9_-]+$', min_length=3, max_length=30)
    password1 = forms.CharField(widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(widget=forms.PasswordInput, required=False)
    
    # Fields for creating a KungfuPerson profile
    style = forms.CharField(max_length=200, required=False)

    # Fields for adding a club membership
    club_url = forms.CharField(max_length=200, required=False)
    club_name = forms.CharField(max_length=200, required=False)
    
    country = forms.ChoiceField() # choices loaded later
    latitude = forms.FloatField(min_value=-90, max_value=90)
    longitude = forms.FloatField(min_value=-180, max_value=180)
    location_description = forms.CharField(max_length=50)
    
    region = GroupedChoiceField(required=False) # choices loaded later
    
    initial_user_id = forms.IntegerField(required=False,
                                         widget=forms.widgets.HiddenInput())

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['country'].choices = [('', '')] + [
          (c.iso_code, c.name) for c in Country.objects.all()]
        self.fields['region'].choices = region_choices()
    
    # Upload a photo is a separate page, because if validation fails we 
    # don't want to tell them to upload it all over again
    #   photo = forms.ImageField(required=False)
    
    # Fields used to create machinetags
    
    # Validation
    def clean_password1(self):
        "Only required if NO openid set for this form"
        if not self.cleaned_data.get('password1', ''):
            raise forms.ValidationError('Password is required')
        return self.cleaned_data['password1']
    
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data.get('password2', '')
        if password1.strip() and password1 != password2:
            raise forms.ValidationError('Passwords must match')
        return self.cleaned_data['password2']
    
    def clean_username(self):
        already_taken = 'That username is unavailable'
        username = self.cleaned_data['username'].lower()
        
        # No reserved usernames, or anything that looks like a 4 digit year 
        if username in RESERVED_USERNAMES or (len(username) == 4 and username.isdigit()):
            raise forms.ValidationError(already_taken)
        
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            pass
        else:
            try:
                user.get_profile()
                raise forms.ValidationError(already_taken)
            except KungfuPerson.DoesNotExist:
                pass
        
        return username
    
    def clean_email(self):
        email = self.cleaned_data['email']
        try:
            user = User.objects.get(email = email)
        except User.DoesNotExist:
            pass
        else:
            raise forms.ValidationError('That e-mail is already in use')
        return email
    
    def clean_region(self):
        # If a region is selected, ensure it matches the selected country
        if self.cleaned_data['region'] and self.cleaned_data.get('country'):
            try:
                region = Region.objects.get(
                    code = self.cleaned_data['region'],
                    country__iso_code = self.cleaned_data.get('country')
                )
            except ObjectDoesNotExist:
                raise forms.ValidationError(
                    'The region you selected does not match the country'
                )
        return self.cleaned_data['region']

    clean_location_description = not_in_the_atlantic
    
    
    def clean_first_name(self):
        if self.cleaned_data['first_name']:
            v = self.cleaned_data['first_name']
            if v.islower() or v.isupper():
                self.cleaned_data['first_name'] = v.title()
        return self.cleaned_data['first_name']

    def clean_last_name(self):
        if self.cleaned_data['last_name']:
            v = self.cleaned_data['last_name']
            if v.islower() or v.isupper():
                self.cleaned_data['last_name'] = v.title()
        return self.cleaned_data['last_name']


class PhotoUploadForm(forms.Form):
    photo = forms.ImageField()
    description = forms.CharField(widget=forms.Textarea, required=False)
    diary_entry = forms.IntegerField(required=False,
                                     widget=forms.widgets.Select()
                                    )

    country = forms.ChoiceField(required=False)
    latitude = forms.FloatField(required=False, min_value=-90, max_value=90)
    longitude = forms.FloatField(required=False, min_value=-180, max_value=180)
    location_description = forms.CharField(required=False, max_length=50)
    region = GroupedChoiceField(required=False)
    
    def __init__(self, *args, **kwargs):
        super(PhotoUploadForm, self).__init__(*args, **kwargs)
        self.fields['country'].choices = [('', '')] + [
          (c.iso_code, c.name) for c in Country.objects.all()]
        self.fields['region'].choices = region_choices()
    
    
    def clear_diary_entry(self):
        if self.cleaned_data['diary_entry']:
            # check that it's valid
            try:
                DiaryEntry.objects.get(id=self.cleaned_data['diary_entry'])
            except DiaryEntry.DoesNotExist:
                raise forms.ValidationError("Invalid diary entry")
            # but we can't check who it belongs to :(
        self.cleaned_data['diary_entry']
            

class PhotoEditForm(forms.Form):
    description = forms.CharField(widget = forms.Textarea)
    #diary_entry = forms.IntegerField(required=False,
    #                                 widget=forms.widgets.Select()
    #                                )
    diary_entry = forms.ChoiceField(required=False)

    country = forms.ChoiceField(required=False)
    latitude = forms.FloatField(required=False, min_value=-90, max_value=90)
    longitude = forms.FloatField(required=False, min_value=-180, max_value=180)
    location_description = forms.CharField(required=False, max_length=50)
    
    region = GroupedChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(PhotoEditForm, self).__init__(*args, **kwargs)
        self.fields['country'].choices = [('', '')] + [
          (c.iso_code, c.name) for c in Country.objects.all()]
        self.fields['region'].choices = region_choices()
        #self.fields['diary_entry'].choices = diary_entry_choices()


class ProfilePhotoUploadForm(forms.Form):
    photo = forms.ImageField()

class ProfilePhotoWebcamForm(forms.Form):
    image_data = forms.CharField(widget=forms.widgets.HiddenInput())
    
    def clean_image_data(self):
        v = self.cleaned_data['image_data']
        tmp_file_path = os.path.join(tempfile.mkdtemp(), 'webcam.jpg')
        open(tmp_file_path, 'wb').write(base64.b64decode(v))
        if not is_jpeg(tmp_file_path):
            raise forms.ValidationError("Not valid JPEG file")
        else:
            os.remove(tmp_file_path)
        return self.cleaned_data['image_data']
    

class DiaryEntryForm(forms.Form):
    title = forms.CharField(max_length=200, widget=forms.widgets.TextInput(attrs=dict(size=40)))
    content = forms.CharField(widget = forms.Textarea)
    country = forms.ChoiceField(required=False)
    latitude = forms.FloatField(required=False, min_value=-90, max_value=90)
    longitude = forms.FloatField(required=False, min_value=-180, max_value=180)
    location_description = forms.CharField(required=False, max_length=50)
    region = GroupedChoiceField(required=False)

    def __init__(self, *args, **kwargs):
        super(DiaryEntryForm, self).__init__(*args, **kwargs)
        self.fields['country'].choices = [('', '')] + [
          (c.iso_code, c.name) for c in Country.objects.all()]

djangopeople/templates/add_video.html
{% extends "base_no_map.html" %}
{% load django_static %}

{% block title %}Add a video to your profile |{% endblock %}

{% block js %}
<script type="text/javascript" src="{% slimfile "/js/add_video.js" %}"></script>
{% endblock %}

{% block extracss %}
<style type="text/css">
#thumbnail-alternatives a { padding:2px; }
#thumbnail-alternatives a.chosen img { border:2px solid red !important; }
</style>
{% endblock %}



{% block header%}
<h1>Add a video to your profile</h1>
{% endblock %}

{% block content %}
        
    	<form method="post" action="{% url add_video person.user.username %}">
	<h2>Link to a YouTube&trade; video?</h2>
        <p><a class="small-text" href="{% url person.view person.user.username %}">(back to your profile)</a></p>

	<div id="profile-box-top">
	</div>
	<div id="profile-box">
	<div id="video-youtube">
        <fieldset>
        <div class="form-field-outer">
		<div class="form-field-left">
            		{{ form.youtube_video_id.errors }}
            		<label for="id_youtube_video_id">Video URL</label>
		</div>

		<div class="form-field-right">
			{{ form.youtube_video_id }}
                        <br/>
                  <span class="pleasewait" style="display:none">
                    <img src="{% staticfile "/static/img/loading.gif" %}" width="16" height="16" alt="Please wait...">
                    Fetching YouTube&trade; video details. Please wait...
                  </span>
		</div>
	</div>
        </fieldset>
        </div><!--/#video-youtube-->

        
        <div id="video-details" style="display:none">    
        
        <fieldset>
        
	
        <div class="form-field-outer" id="thumbnails-outer" style="display:none">
		<div class="form-field-left">
            		<label for="">Choose preferred thumbnail</label>
		</div>

		<div class="form-field-right">
		{{ form.thumbnail_url }}
                        <div id="thumbnail-alternatives">
         		</div>
		</div>
	</div>
	
        
        <div class="form-field-outer" id="preview-outer" style="display:none">
		<div class="form-field-left">
            		<label for="">Preview</label>
		</div>

		<div class="form-field-right">
                &nbsp;
		</div>
	</div>
        

	<div class="form-field-outer" id="embed_src-outer">
		<div class="form-field-left">
            		{{ form.embed_src.errors }}
            		<label for="id_embed_src">Video code</label>
		</div>

		<div class="form-field-right">
			{{ form.embed_src|safe }}
		</div>
	</div>
        
	<div class="form-field-outer">
		<div class="form-field-left">
            		{{ form.title.errors }}
            		<label for="id_title">Title</label>
		</div>

		<div class="form-field-right">
			{{ form.title }}
		</div>
	</div>
        

	<div class="form-field-outer">
		<div class="form-field-left">
            		{{ form.description.errors }}
            		<label for="id_video_description">Description</label>
		</div>

		<div class="form-field-right">
			{{ form.description }}
		</div>
	</div>
        </fieldset>
        </div><!--/#video-details-->
        

	<div class="form-field-outer">      
        
	<div class="form-field-submit">
		<div class="button-outer">
    		<div class="buttonContainer">
    		<input type="submit" value="Add Video">
    		</div>
		</div>
	</div>

	</div>


	</form>
    </div>
    <div id="profile-box-bottom">
    </div>

</div>

	<div id="right-column">
	<div class="right-box">
    	<h3>How to add videos</h3>
	<p>You can add a <a href="http://www.youtube.com">YouTube&trade;</a> video to your profile page by entering the video's URL on the left. You can also add videos from other sites like <a href="http://www.vimeo.com">Vimeo</a> by pasting the 'embed' code.</p>

	<h3>Videos of what?</h3>

	<p>The video can be of yourself (why not show off your patterns a little!) but doesn't have to be. Try to keep it kung fu related, and remember that anything obscene or offensive will be removed.</p>
	</div>
	</div>

	


{% endblock %}

djangopeople/templates/photo_upload_form.html
{% extends "profile.html" %}
{% load django_static %}


{% block title%}{% if page_title %}{{ page_title }}{% else %}Upload photos{% endif %} |{% endblock %}

{% block extracss %}
<link href="/css/swfupload.css" rel="stylesheet" type="text/css">
{% endblock %}

{% block js %}
{% load thumbnail %}
{% if OFFLINE_MODE %}<script type="text/javascript">alert("DOESN'T WORK IN OFFLINE MODE");</script>{% endif %}
<script type="text/javascript" src="/js/photo_add.js"></script>
{% if prefer_multiple %}
<script type="text/javascript" src="/js/swfupload/swfupload.js"></script>
<script type="text/javascript" src="/js/swfupload/swfupload.queue.js"></script>
<script type="text/javascript" src="/js/swfupload/fileprogress.js"></script>
<script type="text/javascript" src="/js/swfupload/handlers.js"></script>
<script type="text/javascript">
var swfu;

$(function() {


  var settings = {
    flash_url : "/js/swfupload/swfupload.swf",
    upload_url: "pre/",
    post_params: {},
    file_size_limit : "100 MB",
    file_types : "*.jpg;*.png;*.gif;*.jpeg",
    file_types_description : "Images",
    file_upload_limit : 20,
    file_queue_limit : 0,
    custom_settings : {
      progressTarget : "fsUploadProgress",
      cancelButtonId : "btnCancel"
    },
    debug: false,
    
    // Button settings
    button_image_url: "/img/XPButtonUploadText_61x22.png",
    button_width: "61",
    button_height: "22",
    button_placeholder_id: "spanButtonPlaceHolder",
    //button_text: '<span class="theFont">Browse</span>',
    //button_text_style: ".theFont { font-size: 16; font-family:Sans-serif, Arial; font-weight:bold;}",
    //button_text_left_padding: 12,
    //button_text_top_padding: 3,
    
    // The event handler functions are defined in handlers.js
    file_queued_handler : fileQueued,
    file_queue_error_handler : fileQueueError,
    file_dialog_complete_handler : fileDialogComplete,
    upload_start_handler : uploadStart,
    upload_progress_handler : uploadProgress,
    upload_error_handler : uploadError,
    upload_success_handler : uploadSuccess,
    upload_complete_handler : uploadComplete,
    queue_complete_handler : queueComplete	// Queue plugin event
    };
    
    swfu = new SWFUpload(settings);

  
});
</script>
{% endif %}

{% endblock %} 

{% block map %}
	<div class="mapContainer major" id="mapWrapper">
	    <div id="gmap">&nbsp;</div>
	</div>
{% endblock %}

{% block content %}

        <div id="content-box">
    	<form enctype="multipart/form-data" method="post" action=".">
            <h2>{% if page_title %}{{ page_title }}{% else %}Upload photos{% endif %}</h2>

	<fieldset>
	{% if photo %}
	{% else %}
        
	<div class="form-field-outer">
        {% if prefer_multiple %}
        <div class="fieldset flash" id="fsUploadProgress" style="display:none">
           <span class="legend">Upload Queue</span>
        </div>

		<div class="form-field-left">
                &nbsp;
		</div>

		<div class="form-field-right">
        <span id="spanButtonPlaceHolder"></span>
        <input type="button" id="btnCancel" value="Cancel all uploads" 
               onclick="swfu.cancelQueue();" disabled="disabled"/>
         <span id="upload-status" style="display:none">0 Files Uploaded</span>
		</div>


        
        {% else %}
		<div class="form-field-left">
                    {{ form.photo.errors }}
                    <label for="id_photo">Photo</label>
		</div>

		<div class="form-field-right">
			{{ form.photo }}
		</div>
        {% endif %}
	</div>
	{% endif %}

	<div class="form-field-outer">
		<div class="form-field-left">
                    {{ form.description.errors }}
                    <label for="id_description">Description</label>
		</div>

		<div class="form-field-right">
			{{ form.description }}
		</div>
	</div>

        {% if  form.diary_entry %}
	<div class="form-field-outer">
		<div class="form-field-left">
                    {{ form.diary_entry.errors }}
                    <label for="id_diary_entry">Blog Post</label>
		</div>

		<div class="form-field-right">
			{{ form.diary_entry }}
		</div>
	</div>
        {% endif %}


	<div class="form-field-outer" id="location">
		<div class="form-field-left">
            		{{ form.location_description.errors }}
            		<label for="id_location_description">Location *</label>
		</div>
		<div class="form-field-right">
			{{ form.location_description }}  <br/><span class="form-hint">(You can customize this if you like - it has been guessed from the map coordinates above.)</span>
		</div>
	</div>

	<div class="form-field-outer" id="country">
		<div class="form-field-left">
            		{{ form.country.errors }}
            		<label for="id_country">Country</label>
		</div>
		<div class="form-field-right">
			{{ form.country }}
		</div>
	</div>

	<div class="form-field-outer" style="display: none;">
		<div class="form-field-left">
            		{{ form.latitude.errors }}
            		<label for="id_latitude">Latitude</label>
		</div>
		<div class="form-field-right">
			{{ form.latitude }}
		</div>
	</div>

	<div class="form-field-outer" style="display: none;">
		<div class="form-field-left">
            		{{ form.longitude.errors }}
            		<label for="id_longitude">Longitude</label>
		</div>
		<div class="form-field-right">
			{{ form.longitude }}
		</div>
	</div>

	<div class="form-field-outer" style="display: none;">
		<div class="form-field-left">
            		{{ form.region.errors }}
            		<label for="id_region">Region</label>
		</div>
		<div class="form-field-right">
			{{ form.region }}
		</div>
	</div>

	<div class="form-field-submit">
		<div class="button-outer">
    		<div class="buttonContainer">
    		<input type="submit" value="{% if button_value %}{{ button_value }}{% else %}Upload{% endif %}">
    		</div>
		</div>
	</div>
	</fieldset>


            </form>
        </div>

	<div id="right-column">
		<div class="right-box">
                {% if not page_title %}
                {% if prefer_multiple %}
                  <p>If you're having problems uploading with the upload widget,
                  <a href=".?prefer=single">try the <strong>single file upload form</strong></a>.
                  </p>
                {% else %}
                  <p>If you're feeling brave,
                  <a href=".?prefer=multiple">try the <strong>fancy multi-file upload form</strong></a>.
                  </p>
                {% endif %}
                {% endif %}
		<p>Geo-tag your resource and let other users see where you took this photo!</p>
		</div>
		{% if photo %}
		<div class="right-box">
		<p>You are currently editing this photo:</p>
		<img src="{% thumbnail photo.photo 100x100 crop %}">
		</div>
		{% endif %}
		</div>
	</div>


{% endblock %}